version: '3.9'
services:
  php:
    image: yiisoftware/yii2-php:8.3-fpm-latest-nginx
    restart: unless-stopped
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    networks:
      booker:
  db:
    image: mariadb:11
    restart: unless-stopped
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      booker:
networks:
  booker:
volumes:
  db_data:
